---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.7
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[elasticsearch-cluster::default]
    attributes:
      elasticsearch:
        config:
          cluster.name: "foo"
  - name: version5
    run_list:
      - recipe[elasticsearch-cluster::default]
    attributes:
      elasticsearch:
        config:
          cluster.name: "foo"
        version: 5.1.2
