---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.7
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[elasticsearch-cluster::default]
      - recipe[elasticsearch-cluster::plugins]
    attributes:
      elasticsearch:
        config:
          cluster.name: "foo"
        plugins:
          head:
            install_source: mobz/elasticsearch-head
  - name: version5
    run_list:
      - recipe[elasticsearch-cluster::default]
      - recipe[elasticsearch-cluster::plugins]
    attributes:
      elasticsearch:
        config:
          cluster.name: "foo"
        plugins:
          x-pack:
            install_source: x-pack -b
        version: 5.1.2
